					'services' => [
						[
							'slug' => 'schemas-2d',
							'title' => '2D Schematics',
							'tagline' => 'Detailed technical plans and schematics',
							'description' => 'Create precise and informative technical plans for your architectural projects. Our 2D schematics include floor plans, elevations, sections, and detail drawings, all executed according to professional architectural standards.',
							'heroImage' => [
								'id' => 'service-hero-2d-schemas',
								'src' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=2070&q=80',
								'alt' => 'Detailed 2D architectural plans',
							],
							'benefits' => [
								[
									'id' => 'benefit-2d-1',
									'title' => 'Technical Precision',
									'description' => 'Plans executed according to architectural standards with exact dimensions and clear annotations.',
									'icon' => 'ruler',
								],
								[
									'id' => 'benefit-2d-2',
									'title' => 'Visual Clarity',
									'description' => 'Easy-to-understand representations for all project stakeholders, from architects to property owners.',
									'icon' => 'eye',
								],
								[
									'id' => 'benefit-2d-3',
									'title' => 'Complete Documentation',
									'description' => 'Floor plans, elevations, sections, and details for comprehensive architectural documentation.',
									'icon' => 'layers',
								],
								[
									'id' => 'benefit-2d-4',
									'title' => 'Standards Compliant',
									'description' => 'Adherence to professional architectural presentation and symbology standards.',
									'icon' => 'check-circle',
								],
							],
							'process' => [
								[
									'id' => '2d-step-1',
									'title' => 'Data Collection',
									'description' => 'Gathering and studying existing plans and technical documents.',
									'icon' => 'circle',
									'details' => 'We receive and analyze your architectural plans to understand the spatial and structural characteristics of your project. This step allows us to identify optimal viewing angles and key elements to highlight.',
								],
								[
									'id' => '2d-step-2',
									'title' => '2D Modeling',
									'description' => 'Creating precise 2D schematics using professional tools.',
									'icon' => 'square',
									'details' => 'We create accurate 2D representations respecting proportions and scales. Each schematic is enriched with contextual elements (vegetation, urban furniture, people) for better spatial understanding.',
								],
								[
									'id' => '2d-step-3',
									'title' => 'Finalization & Delivery',
									'description' => 'Optimization and multi-format export.',
									'icon' => 'triangle',
									'details' => 'We refine graphic details, adjust colors and materials, then deliver your schematics in formats adapted to your needs (PDF, high-resolution PNG, print formats).',
								],
							],
							'images' => [
								[
									'id' => 'schemas-img-1',
									'src' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e',
									'alt' => 'Isometric view of architectural complex',
								],
								[
									'id' => 'schemas-img-2',
									'src' => 'https://images.unsplash.com/photo-1487958449943-2429e8be8625',
									'alt' => 'Detailed architectural section of building',
								],
								[
									'id' => 'schemas-img-3',
									'src' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
									'alt' => 'Axonometric schematic with urban environment',
								],
								[
									'id' => 'schemas-img-4',
									'src' => 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368',
									'alt' => 'Architectural facade with contextual elements',
								],
							],
							'relatedProjects' => [],
							'icon' => 'layers',
							'category' => '2D Visualization',
							'ctaLabel' => 'Request a quote',
							'ctaHref' => '/en/contact',
						],
						[
							'slug' => 'rendus-3d-fixes',
							'title' => '3D Fixed Renders',
							'tagline' => 'Photorealistic interior and exterior visualizations',
							'description' => 'At Parallax Studio, we pay tremendous attention to detail to create realistic, high-quality renders with the goal of presenting the image you want. With resolutions ranging from 2K to 16K, for mobile supports or giant format prints, we custom-create your interior and exterior renders.',
							'heroImage' => [
								'id' => 'hero-rendus-3d',
								'src' => 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
								'alt' => 'Photorealistic 3D render of modern interior',
							],
							'benefits' => [
								[
									'id' => 'benefit-rendus-1',
									'title' => 'Realistic and Detailed Visualization',
									'description' => 'Fixed 3D renders offer a photorealistic representation of the architectural project. They allow clients and investors to precisely visualize the appearance and characteristics of the building before it is even built.',
									'icon' => 'home',
								],
								[
									'id' => 'benefit-rendus-2',
									'title' => 'Immersivity and Client Engagement',
									'description' => '3D renders create an immersive experience that allows viewers to project themselves into the architectural space. They strengthen engagement and interest by enabling better understanding of spatial layout and proportions.',
									'icon' => 'home',
								],
								[
									'id' => 'benefit-rendus-3',
									'title' => 'Powerful Marketing Tool',
									'description' => 'Fixed 3D renders are essential for marketing and promotion of real estate projects. Usable in brochures, websites, and presentations, they attract the attention of potential buyers and highlight project features.',
									'icon' => 'home',
								],
								[
									'id' => 'benefit-rendus-4',
									'title' => 'Reduction of Design Errors',
									'description' => 'By visualizing the project in a virtual environment, designers can identify design, ergonomics, or circulation problems and make necessary adjustments before construction begins.',
									'icon' => 'home',
								],
							],
							'process' => [
								[
									'id' => 'process-rendus-1',
									'title' => '3D Modeling',
									'description' => 'Creating detailed architectural model',
									'icon' => 'circle',
									'details' => 'We build a precise 3D model of your project scrupulously respecting plans, dimensions, and technical specifications. Each architectural element is modeled with particular attention to detail.',
								],
								[
									'id' => 'process-rendus-2',
									'title' => 'Materials and Lighting',
									'description' => 'Applying textures and lighting setup',
									'icon' => 'square',
									'details' => 'We apply photorealistic materials (wood, stone, glass, metals) and configure realistic natural and artificial lighting to create an atmosphere faithful to your vision and showcase the architecture.',
								],
								[
									'id' => 'process-rendus-3',
									'title' => 'Rendering and Post-Production',
									'description' => 'Final calculation and image optimization',
									'icon' => 'triangle',
									'details' => 'We perform high-resolution rendering (2K to 16K) and refine each image in post-production to adjust colors, contrasts, and details. Delivery in formats adapted to your marketing needs.',
								],
							],
							'images' => [
								[
									'id' => 'rendus-img-1',
									'src' => 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
									'alt' => 'Photorealistic interior render of modern living room',
								],
								[
									'id' => 'rendus-img-2',
									'src' => 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea',
									'alt' => 'Exterior render of contemporary villa',
								],
								[
									'id' => 'rendus-img-3',
									'src' => 'https://images.unsplash.com/photo-1600210492493-0946911123ea',
									'alt' => '3D render of designer kitchen',
								],
								[
									'id' => 'rendus-img-4',
									'src' => 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde',
									'alt' => 'Architectural night render with lighting',
								],
								[
									'id' => 'rendus-img-5',
									'src' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
									'alt' => 'High-resolution render of luxury bedroom',
								],
							],
							'relatedProjects' => [],
							'icon' => 'home',
							'category' => '3D Visualization',
							'ctaLabel' => 'Request a quote',
							'ctaHref' => '/en/contact',
						],
						[
							'slug' => 'animations-video',
							'title' => 'Video Animations',
							'tagline' => '3D animated videos that bring your projects to life',
							'description' => 'The effectiveness of 3D animation videos is no longer in question. Using an animated video propels your real estate projects in an exceptional way. Broadcast on social networks or websites, 3D animation will mark minds and have a positive impact on your prospects. From 480p to 4K, at 30 or 60 fps, with professional editing and custom soundtrack.',
							'heroImage' => [
								'id' => 'hero-animations',
								'src' => 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d',
								'alt' => 'Architectural animation video production',
							],
							'benefits' => [
								[
									'id' => 'benefit-animations-1',
									'title' => 'Total and Dynamic Immersion',
									'description' => 'Animated videos allow viewers to fully immerse themselves in the architectural project. By offering a dynamic and fluid perspective, they can explore each space, move through different rooms, and appreciate architectural details from different angles.',
									'icon' => 'film',
								],
								[
									'id' => 'benefit-animations-2',
									'title' => 'Captivating Visual Storytelling',
									'description' => 'Animated videos allow telling a captivating visual story around the project. By adding narrative elements, natural light play, and atmospheric scenes, they create an immersive experience that arouses interest and emotion.',
									'icon' => 'film',
								],
								[
									'id' => 'benefit-animations-3',
									'title' => 'Market Differentiation',
									'description' => 'High-quality animated videos constitute an essential differentiation tool in a competitive market. They capture the attention of potential clients by offering an immersive and memorable experience that stands out.',
									'icon' => 'film',
								],
								[
									'id' => 'benefit-animations-4',
									'title' => 'Effective Fundraising',
									'description' => '3D animation videos are very useful for raising funds from investors. They represent the project as a whole, highlight its strengths, and allow convincing through a dynamic and professional presentation.',
									'icon' => 'film',
								],
							],
							'process' => [
								[
									'id' => 'process-animations-1',
									'title' => 'Scriptwriting and Storyboard',
									'description' => 'Designing the visual journey',
									'icon' => 'circle',
									'details' => 'We develop a detailed script and storyboard defining camera movements, transitions, points of interest to highlight, and video pacing to create a coherent and engaging narrative.',
								],
								[
									'id' => 'process-animations-2',
									'title' => 'Animation and Rendering',
									'description' => 'Creating animated sequences',
									'icon' => 'square',
									'details' => 'We animate the camera through spaces, add life elements (people, vehicles, nature), and perform high-definition rendering of each frame with particular attention to fluidity and realism.',
								],
								[
									'id' => 'process-animations-3',
									'title' => 'Editing and Finalization',
									'description' => 'Professional post-production',
									'icon' => 'triangle',
									'details' => 'We perform final editing, add music, sound effects, transitions, logo and text overlays, then deliver the video in the desired format and resolution (up to 4K 60fps).',
								],
							],
							'images' => [
								[
									'id' => 'animations-img-1',
									'src' => 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d',
									'alt' => '3D architectural animation scene',
								],
								[
									'id' => 'animations-img-2',
									'src' => 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb',
									'alt' => 'Architectural walkthrough video sequence',
								],
								[
									'id' => 'animations-img-3',
									'src' => 'https://images.unsplash.com/photo-1536440136628-849c177e76a1',
									'alt' => 'Professional video production',
								],
								[
									'id' => 'animations-img-4',
									'src' => 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04',
									'alt' => 'Real estate project animation',
								],
							],
							'relatedProjects' => [],
							'icon' => 'film',
							'category' => '3D Video',
							'ctaLabel' => 'Request a quote',
							'ctaHref' => '/en/contact',
						],
						[
							'slug' => 'panoramiques-360',
							'title' => '360° Panoramic Renders',
							'tagline' => 'Immersive 360-degree experiences',
							'description' => '360° panoramic 3D renders allow total immersion in the architectural environment. Accessible via smartphone, tablet, or PC, they offer viewers the possibility to visualize the project interior from all angles in an interactive and intuitive way, creating an engaging experience that facilitates projection and decision-making.',
							'heroImage' => [
								'id' => 'hero-panoramiques',
								'src' => 'https://images.unsplash.com/photo-1617806118233-18e1de247200',
								'alt' => '360° panoramic view of architectural space',
							],
							'benefits' => [
								[
									'id' => 'benefit-panoramiques-1',
									'title' => 'Total Interactive Immersion',
									'description' => '360° panoramic renders allow complete immersion in the architectural environment. Viewers can visualize the space from all angles, creating an unprecedented immersive and engaging experience.',
									'icon' => 'globe',
								],
								[
									'id' => 'benefit-panoramiques-2',
									'title' => 'Human-Scale Presentation',
									'description' => '360° renders show the project interior at human scale. Viewers feel as if they are physically present in the space, giving them better understanding of proportions and layout.',
									'icon' => 'globe',
								],
								[
									'id' => 'benefit-panoramiques-3',
									'title' => 'Multi-Platform Accessibility',
									'description' => '360° panoramics can be viewed via smartphone, tablet, or PC, making them accessible everywhere and anytime. Perfect for sharing on social networks and digital distribution.',
									'icon' => 'globe',
								],
								[
									'id' => 'benefit-panoramiques-4',
									'title' => 'Reduction of Uncertainties',
									'description' => 'By allowing detailed and realistic visualization of the project interior, 360° renders help reduce uncertainties of potential clients and facilitate more informed and confident decision-making.',
									'icon' => 'globe',
								],
							],
							'process' => [
								[
									'id' => 'process-panoramiques-1',
									'title' => 'Viewpoint Positioning',
									'description' => 'Selecting strategic angles',
									'icon' => 'circle',
									'details' => 'We identify optimal locations for 360° shots to cover the entire project and highlight each space. Each viewpoint is strategically chosen for smooth exploration.',
								],
								[
									'id' => 'process-panoramiques-2',
									'title' => 'Panoramic Rendering',
									'description' => 'Creating 360° spherical images',
									'icon' => 'square',
									'details' => 'We generate high-resolution 360° panoramic renders for each viewpoint. These spherical images capture the entire environment with photorealistic realism and attention to detail.',
								],
								[
									'id' => 'process-panoramiques-3',
									'title' => 'Interactive Integration',
									'description' => 'Configuring 360° navigation',
									'icon' => 'triangle',
									'details' => 'We integrate 360° renders into an interactive platform (Klapty type) allowing smooth navigation between spaces, with clickable points of interest and compatibility with all platforms (mobile, tablet, desktop).',
								],
							],
							'images' => [
								[
									'id' => 'panoramiques-img-1',
									'src' => 'https://images.unsplash.com/photo-1617806118233-18e1de247200',
									'alt' => '360° panoramic render of living room',
								],
								[
									'id' => 'panoramiques-img-2',
									'src' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
									'alt' => '360° immersive view of commercial space',
								],
								[
									'id' => 'panoramiques-img-3',
									'src' => 'https://images.unsplash.com/photo-1615529182904-14819c35db37',
									'alt' => 'Interactive panorama of modern office',
								],
								[
									'id' => 'panoramiques-img-4',
									'src' => 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0',
									'alt' => '360° experience in apartment',
								],
							],
							'relatedProjects' => [],
							'icon' => 'globe',
							'category' => '360° Immersion',
							'ctaLabel' => 'Request a quote',
							'ctaHref' => '/en/contact',
						],
						[
							'slug' => 'generation-artificielle',
							'title' => 'AI Generation',
							'tagline' => 'Fast AI renders and multiple variations',
							'description' => '3D architectural renders generated by artificial intelligence offer speed, flexibility, and precision to considerably accelerate the design process. While AI generation cannot yet replace traditional precision, it offers revolutionary tools that facilitate the process and save time with photorealistic results.',
							'heroImage' => [
								'id' => 'hero-ia',
								'src' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995',
								'alt' => 'Architectural render generated by artificial intelligence',
							],
							'benefits' => [
								[
									'id' => 'benefit-ia-1',
									'title' => 'Unmatched Speed and Efficiency',
									'description' => 'AI-generated renders can be produced in hours or less depending on complexity. This allows architects to propose variations and alternatives at a much faster pace than traditional methods.',
									'icon' => 'brain',
								],
								[
									'id' => 'benefit-ia-2',
									'title' => 'Infinite Flexibility and Variations',
									'description' => 'AI allows generating a wide variety of renders according to client needs. Experiment with different configurations, styles, materials, and finishes to respond to specific requirements and explore all possibilities.',
									'icon' => 'brain',
								],
								[
									'id' => 'benefit-ia-3',
									'title' => 'Considerably Reduced Cost',
									'description' => 'Using AI to generate renders often reduces production costs compared to traditional methods. This allows presenting concepts cost-effectively and efficiently, ideal for preliminary explorations.',
									'icon' => 'brain',
								],
								[
									'id' => 'benefit-ia-4',
									'title' => 'Personalization and Uniqueness',
									'description' => 'AI renders can be personalized to reflect specific project characteristics. Create unique and custom images that exactly match client needs and preferences with impressive realism.',
									'icon' => 'brain',
								],
							],
							'process' => [
								[
									'id' => 'process-ia-1',
									'title' => 'Brief and References',
									'description' => 'Collecting information and visuals',
									'icon' => 'circle',
									'details' => 'We gather your existing photographs, conceptual sketches, stylistic references, and specifications. This step allows calibrating AI to generate renders aligned with your creative vision.',
								],
								[
									'id' => 'process-ia-2',
									'title' => 'AI Generation',
									'description' => 'Producing multiple variations',
									'icon' => 'square',
									'details' => 'We use advanced AI algorithms to rapidly generate multiple variations of photorealistic renders. Each iteration explores different design, material, lighting, and ambiance options.',
								],
								[
									'id' => 'process-ia-3',
									'title' => 'Selection and Refinement',
									'description' => 'Optimizing selected renders',
									'icon' => 'triangle',
									'details' => 'We select the best proposals together and refine them through post-production to ensure quality and consistency. Rapid delivery of final renders in desired formats.',
								],
							],
							'images' => [
								[
									'id' => 'ia-img-1',
									'src' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995',
									'alt' => 'Architectural render created by AI',
								],
								[
									'id' => 'ia-img-2',
									'src' => 'https://images.unsplash.com/photo-1676277791608-b3fa03a5a375',
									'alt' => 'Design variations generated by artificial intelligence',
								],
								[
									'id' => 'ia-img-3',
									'src' => 'https://images.unsplash.com/photo-1676299081847-824916de030a',
									'alt' => 'AI reinterpretation of existing space',
								],
								[
									'id' => 'ia-img-4',
									'src' => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb',
									'alt' => 'Conceptual exploration by AI',
								],
							],
							'relatedProjects' => [],
							'icon' => 'brain',
							'category' => 'Artificial Intelligence',
							'ctaLabel' => 'Request a quote',
							'ctaHref' => '/en/contact',
						],
						[
							'slug' => 'experiences-virtuelles',
							'title' => 'Virtual Experiences',
							'tagline' => 'Virtual reality and immersive interactive tours',
							'description' => 'Virtual reality and virtual tours offer the most technological and immersive experience to present your architectural projects. Experience any project from the inside, 1:1 scale, before the first stone is laid. Explore spaces freely, feel volumes differently, and impress your clients with a guaranteed wow effect.',
							'heroImage' => [
								'id' => 'hero-vr',
								'src' => 'https://images.unsplash.com/photo-1617802690658-1173a812650d',
								'alt' => 'Person using virtual reality headset to explore architectural project',
							],
							'benefits' => [
								[
									'id' => 'benefit-vr-1',
									'title' => 'Total Immersion at Human Scale',
									'description' => 'VR and virtual tours allow users to fully immerse themselves in the project environment. By wearing a VR headset or navigating in 360°, they feel physically present, allowing appreciation of real proportions.',
									'icon' => 'vr',
								],
								[
									'id' => 'benefit-vr-2',
									'title' => 'Interactivity and Personalization',
									'description' => 'Virtual experiences offer unprecedented interactivity. Users can move freely, modify textures, change colors, explore different design options, and personalize their viewing experience.',
									'icon' => 'vr',
								],
								[
									'id' => 'benefit-vr-3',
									'title' => 'Maximum Accessibility and Flexibility',
									'description' => 'Virtual tours can be viewed via smartphone, tablet, or PC, making the project accessible everywhere and anytime. Clients can visit the project remotely, reducing time and costs of physical visits.',
									'icon' => 'vr',
								],
								[
									'id' => 'benefit-vr-4',
									'title' => 'Wow Effect and Differentiation',
									'description' => 'VR experiences and virtual tours constitute powerful differentiation tools in the market. They offer a unique and memorable experience that impresses potential clients and facilitates major sales closures.',
									'icon' => 'vr',
								],
							],
							'process' => [
								[
									'id' => 'process-vr-1',
									'title' => 'Optimized VR Modeling',
									'description' => 'Creating interactive environments',
									'icon' => 'circle',
									'details' => 'We create 3D models optimized for virtual reality and virtual tours, respecting technical performance constraints while maximizing realism. Each space is designed for smooth and immersive navigation.',
								],
								[
									'id' => 'process-vr-2',
									'title' => 'Interactive Configuration',
									'description' => 'Integrating VR functionalities',
									'icon' => 'square',
									'details' => 'We configure interactions (navigation, teleportation, material modification), points of interest, informative hotspots, and guided tours. For virtual tours, we create navigation structure between spaces.',
								],
								[
									'id' => 'process-vr-3',
									'title' => 'Deployment and Support',
									'description' => 'Multi-platform delivery',
									'icon' => 'triangle',
									'details' => 'We deliver VR experience compatible with major headsets (Oculus, HTC Vive) and/or online accessible virtual tour on all platforms. Training and technical support included for optimal use with your clients.',
								],
							],
							'images' => [
								[
									'id' => 'vr-img-1',
									'src' => 'https://images.unsplash.com/photo-1617802690658-1173a812650d',
									'alt' => 'Architectural virtual reality experience',
								],
								[
									'id' => 'vr-img-2',
									'src' => 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac',
									'alt' => 'Navigation in real estate virtual tour',
								],
								[
									'id' => 'vr-img-3',
									'src' => 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620',
									'alt' => 'VR headset for architectural exploration',
								],
								[
									'id' => 'vr-img-4',
									'src' => 'https://images.unsplash.com/photo-1535223289827-42f1e9919769',
									'alt' => 'Interactive virtual tour interface',
								],
								[
									'id' => 'vr-img-5',
									'src' => 'https://images.unsplash.com/photo-1626379953822-baec19c3accd',
									'alt' => 'Immersive presentation in virtual reality',
								],
								[
									'id' => 'vr-img-6',
									'src' => 'https://images.unsplash.com/photo-1610618016289-d684b72b8787',
									'alt' => 'Virtual tour of architectural project',
								],
							],
							'relatedProjects' => [],
							'icon' => 'vr',
							'category' => 'Virtual Reality',
							'ctaLabel' => 'Request a quote',
							'ctaHref' => '/en/contact',
						],
					],
