					'services' => [
						[
							'slug' => '2d-schemas',
							'title' => 'Schémas 2D',
							'tagline' => 'Plans et schémas techniques détaillés',
							'description' => 'Créez des plans techniques précis et informatifs pour vos projets architecturaux. Nos schémas 2D incluent des plans d\'étage, des élévations, des coupes et des plans de détail, tous exécutés selon les normes architecturales professionnelles.',
							'heroImage' => [
								'id' => 'service-hero-2d-schemas',
								'src' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=2070&q=80',
								'alt' => 'Plans architecturaux détaillés en 2D',
							],
							'benefits' => [
								[
									'id' => 'benefit-2d-1',
									'title' => 'Précision Technique',
									'description' => 'Plans exécutés selon les normes architecturales avec dimensions exactes et annotations claires.',
									'icon' => 'ruler',
								],
								[
									'id' => 'benefit-2d-2',
									'title' => 'Clarté Visuelle',
									'description' => 'Représentations faciles à comprendre pour tous les acteurs du projet, architectes comme propriétaires.',
									'icon' => 'eye',
								],
								[
									'id' => 'benefit-2d-3',
									'title' => 'Documentation Complète',
									'description' => 'Plans d\'étage, élévations, coupes et détails pour une documentation architecturale exhaustive.',
									'icon' => 'layers',
								],
								[
									'id' => 'benefit-2d-4',
									'title' => 'Normes Conformes',
									'description' => 'Respect des standards de présentation et de symbolique architecturale professionnelle.',
									'icon' => 'check-circle',
								],
							],
							'process' => [
								[
									'id' => '2d-step-1',
									'title' => 'Collecte des Données',
									'description' => 'Récupération et étude des plans et documents techniques existants.',
									'icon' => 'circle',
									'details' => [
										'Réception des fichiers DWG, PDF ou images scannées',
										'Vérification des dimensions et de la cohérence des données',
										'Clarification des besoins spécifiques avec le client',
									],
								],
								[
									'id' => '2d-step-2',
									'title' => 'Modélisation 2D',
									'description' => 'Création des schémas 2D précis en utilisant les outils professionnels.',
									'icon' => 'circle',
									'details' => [
										'Dessin des plans d\'étage avec tous les éléments architecturaux',
										'Création des élévations et coupes techniques',
										'Ajout des dimensions et des annotations',
									],
								],
								[
									'id' => '2d-step-3',
									'title' => 'Annotations & Détails',
									'description' => 'Ajout des informations techniques et des appels de détail.',
									'icon' => 'circle',
									'details' => [
										'Notation des matériaux et finitions',
										'Appels de détail pour les éléments spécifiques',
										'Légendes et symboles architecturaux standards',
									],
								],
								[
									'id' => '2d-step-4',
									'title' => 'Révision & Livraison',
									'description' => 'Vérification finale et exportation dans les formats requis.',
									'icon' => 'circle',
									'details' => [
										'Contrôle qualité complet des plans',
										'Révisions basées sur vos retours',
										'Exportation en PDF, DWG et images haute résolution',
									],
								],
							],
							'relatedProjects' => [],
							'icon' => 'square',
							'category' => 'Documentation',
							'ctaLabel' => 'Demander un devis',
							'ctaHref' => '/contact',
						],
						[
							'slug' => '3d-fixed-renders',
							'title' => 'Rendus 3D Fixes',
							'tagline' => 'Images statiques photoréalistes haute résolution',
							'description' => 'Obtenez des images 3D époustouflantes et photoréalistes de votre projet. Nos rendus fixes capturent chaque détail avec une qualité cinématographique, permettant une visualisation complète de votre vision avant la construction.',
							'heroImage' => [
								'id' => 'service-hero-3d-fixed',
								'src' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2070&q=80',
								'alt' => 'Rendu 3D moderne et photoréaliste',
							],
							'benefits' => [
								[
									'id' => 'benefit-3d-1',
									'title' => 'Photoréalisme Extrême',
									'description' => 'Rendus ultraphotorécalistes avec éclairage global, reflets et ombres dynamiques.',
									'icon' => 'sparkles',
								],
								[
									'id' => 'benefit-3d-2',
									'title' => 'Contexte Environnant',
									'description' => 'Intégration intelligente du projet dans l\'environnement réel avec végétation et paysage.',
									'icon' => 'trees',
								],
								[
									'id' => 'benefit-3d-3',
									'title' => 'Multiples Perspectives',
									'description' => 'Rendus variés : vues diurnes/nocturnes, saisons différentes, angles multiples.',
									'icon' => 'camera',
								],
								[
									'id' => 'benefit-3d-4',
									'title' => 'Haute Résolution',
									'description' => 'Images 4K et ultra HD optimisées pour impression et présentation numérique.',
									'icon' => 'monitor',
								],
							],
							'process' => [
								[
									'id' => '3d-step-1',
									'title' => 'Création du Modèle 3D',
									'description' => 'Modélisation détaillée basée sur vos plans architecturaux.',
									'icon' => 'circle',
									'details' => [
										'Import et conversion de vos fichiers CAO/BIM',
										'Modélisation 3D haute fidélité de tous les éléments',
										'Ajout des matériaux et textures initiales',
									],
								],
								[
									'id' => '3d-step-2',
									'title' => 'Mise en Place de la Scène',
									'description' => 'Configuration de l\'environnement et de l\'éclairage.',
									'icon' => 'circle',
									'details' => [
										'Intégration du contexte environnant (terrain, végétation)',
										'Configuration de l\'éclairage naturel réaliste',
										'Ajout des objets de décoration et mobilier',
									],
								],
								[
									'id' => '3d-step-3',
									'title' => 'Finitions & Matériaux',
									'description' => 'Raffinement des matériaux pour un réalisme maximal.',
									'icon' => 'circle',
									'details' => [
										'Application des textures précises et détaillées',
										'Ajout des reflets, brillance et rugosité réalistes',
										'Configuration des propriétés de chaque matériau',
									],
								],
								[
									'id' => '3d-step-4',
									'title' => 'Rendu Final & Post-Production',
									'description' => 'Rendu haute résolution et retouches finales.',
									'icon' => 'circle',
									'details' => [
										'Rendu 4K avec algorithmes avancés',
										'Post-production légère (couleur, contraste)',
										'Livraison en multiple formats et résolutions',
									],
								],
							],
							'relatedProjects' => [],
							'icon' => 'image',
							'category' => 'Visualisation',
							'ctaLabel' => 'Demander un devis',
							'ctaHref' => '/contact',
						],
						[
							'slug' => 'video-animations',
							'title' => 'Animations Vidéo',
							'tagline' => 'Séquences vidéo cinématographiques et engageantes',
							'description' => 'Animez votre projet avec des vidéos cinématographiques spectaculaires. Nos animations capturent le mouvement, la fluidité et les changements dynamiques pour créer une expérience immersive et mémorable de votre vision.',
							'heroImage' => [
								'id' => 'service-hero-video-animation',
								'src' => 'https://images.unsplash.com/photo-1611339555312-e607c90352fd?auto=format&fit=crop&w=2070&q=80',
								'alt' => 'Séquence vidéo cinématographique',
							],
							'benefits' => [
								[
									'id' => 'benefit-video-1',
									'title' => 'Cinématographie Professionnelle',
									'description' => 'Mouvements de caméra fluides et cinématiques pour une présentation spectaculaire.',
									'icon' => 'film',
								],
								[
									'id' => 'benefit-video-2',
									'title' => 'Transitions Dynamiques',
									'description' => 'Transitions lisses et effets visuels pour un flux narratif captivant.',
									'icon' => 'zap',
								],
								[
									'id' => 'benefit-video-3',
									'title' => 'Narration Immersive',
									'description' => 'Exploration complète du projet avec mouvements de caméra intelligent et progression logique.',
									'icon' => 'compass',
								],
								[
									'id' => 'benefit-video-4',
									'title' => 'Qualité Broadcast',
									'description' => 'Production vidéo 4K professionnelle adaptée à tous les canaux de distribution.',
									'icon' => 'broadcast',
								],
							],
							'process' => [
								[
									'id' => 'video-step-1',
									'title' => 'Concept & Storyboard',
									'description' => 'Définition de la narration et du parcours vidéo.',
									'icon' => 'circle',
									'details' => [
										'Briefing créatif et définition des objectifs',
										'Création d\'un storyboard détaillé',
										'Planification des mouvements de caméra',
									],
								],
								[
									'id' => 'video-step-2',
									'title' => 'Modélisation & Préparation',
									'description' => 'Création du modèle 3D complet et environnement.',
									'icon' => 'circle',
									'details' => [
										'Modélisation 3D haute fidélité',
										'Configuration des matériaux et textures',
										'Intégration de l\'environnement et contexte',
									],
								],
								[
									'id' => 'video-step-3',
									'title' => 'Animation & Simulation',
									'description' => 'Animation des mouvements de caméra et éléments dynamiques.',
									'icon' => 'circle',
									'details' => [
										'Animation des mouvements de caméra cinématiques',
										'Simulation des éléments dynamiques (eau, particules)',
										'Ajout des transitions et effets spéciaux',
									],
								],
								[
									'id' => 'video-step-4',
									'title' => 'Rendu & Post-Production',
									'description' => 'Rendu vidéo final et montage professionnel.',
									'icon' => 'circle',
									'details' => [
										'Rendu vidéo 4K avec calculs avancés',
										'Montage et ajustement du timing',
										'Étalonnage couleur et effets sonores/musique',
									],
								],
							],
							'relatedProjects' => [],
							'icon' => 'video',
							'category' => 'Animation',
							'ctaLabel' => 'Demander un devis',
							'ctaHref' => '/contact',
						],
						[
							'slug' => '360-panoramas',
							'title' => 'Panoramiques 360°',
							'tagline' => 'Vues panoramiques immersives à 360 degrés',
							'description' => 'Immergez vos clients dans votre projet avec des panoramiques 360 degrés interactifs. Ces vues immersives permettent une exploration complète du projet sous tous les angles, créant une expérience d\'exploration intuitive et captivante.',
							'heroImage' => [
								'id' => 'service-hero-360-panorama',
								'src' => 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?auto=format&fit=crop&w=2070&q=80',
								'alt' => 'Vue panoramique 360 degrés',
							],
							'benefits' => [
								[
									'id' => 'benefit-360-1',
									'title' => 'Exploration Complète',
									'description' => 'Visualisation à 360 degrés permettant l\'exploration de tous les angles et perspectives.',
									'icon' => 'globe',
								],
								[
									'id' => 'benefit-360-2',
									'title' => 'Interaction Intuitive',
									'description' => 'Navigation fluide et intuitive pour une expérience utilisateur optimale sur desktop et mobile.',
									'icon' => 'hand-pointer',
								],
								[
									'id' => 'benefit-360-3',
									'title' => 'Immersion Maximale',
									'description' => 'Champs de vision ultra-larges créant une sensation d\'immersion complète dans l\'espace.',
									'icon' => 'maximize-2',
								],
								[
									'id' => 'benefit-360-4',
									'title' => 'Compatibilité VR',
									'description' => 'Affichage compatible avec les casques de réalité virtuelle pour une expérience immersive totale.',
									'icon' => 'headphones',
								],
							],
							'process' => [
								[
									'id' => '360-step-1',
									'title' => 'Positionnement des Points de Vue',
									'description' => 'Définition des emplacements stratégiques pour la capture.',
									'icon' => 'circle',
									'details' => [
										'Sélection des points de vue clés du projet',
										'Planification des perspectives les plus pertinentes',
										'Définition des hauteurs et angles d\'observation',
									],
								],
								[
									'id' => '360-step-2',
									'title' => 'Modélisation & Scénario',
									'description' => 'Création du modèle 3D complet et configuration.',
									'icon' => 'circle',
									'details' => [
										'Modélisation 3D détaillée et environnement complet',
										'Configuration des matériaux photorécalistes',
										'Ajustement de l\'éclairage pour chaque point de vue',
									],
								],
								[
									'id' => '360-step-3',
									'title' => 'Génération des Vues 360°',
									'description' => 'Rendu des panoramiques à 360 degrés.',
									'icon' => 'circle',
									'details' => [
										'Rendu sphérique 360° haute résolution',
										'Traitement des images panoramiques',
										'Optimisation pour une lecture fluide',
									],
								],
								[
									'id' => '360-step-4',
									'title' => 'Intégration Interactive',
									'description' => 'Configuration et intégration dans une plateforme interactive.',
									'icon' => 'circle',
									'details' => [
										'Programmation de l\'interface de navigation',
										'Tests de compatibilité (desktop, mobile, VR)',
										'Optimisation des performances de chargement',
									],
								],
							],
							'relatedProjects' => [],
							'icon' => 'circle',
							'category' => 'Expérience',
							'ctaLabel' => 'Demander un devis',
							'ctaHref' => '/contact',
						],
						[
							'slug' => 'ai-generation',
							'title' => 'Génération Artificielle',
							'tagline' => 'Génération d\'images innovantes basée sur l\'intelligence artificielle',
							'description' => 'Explorez de nouvelles perspectives de votre projet grâce à la génération d\'images par IA. Cette technologie innovante crée des variantes, des style alternatives et des explorations créatives de votre vision architecturale.',
							'heroImage' => [
								'id' => 'service-hero-ai-generation',
								'src' => 'https://images.unsplash.com/photo-1677442d019cecf8978e4553744bb20e5c5ecc26d?auto=format&fit=crop&w=2070&q=80',
								'alt' => 'Génération d\'image par intelligence artificielle',
							],
							'benefits' => [
								[
									'id' => 'benefit-ai-1',
									'title' => 'Exploration Créative',
									'description' => 'Génération rapide de multiples variantes et styles pour explorer différentes directions créatives.',
									'icon' => 'lightbulb',
								],
								[
									'id' => 'benefit-ai-2',
									'title' => 'Itération Rapide',
									'description' => 'Créer des variations de votre projet en heures plutôt qu\'en jours pour accélérer le processus de conception.',
									'icon' => 'zap',
								],
								[
									'id' => 'benefit-ai-3',
									'title' => 'Styles Variés',
									'description' => 'Exploration de différents styles architecturaux, matériaux et aménagements d\'une manière rapide et innovante.',
									'icon' => 'palette',
								],
								[
									'id' => 'benefit-ai-4',
									'title' => 'Optimisation Efficace',
									'description' => 'Combinez l\'IA avec votre expertise créative pour affiner et optimiser les résultats générés.',
									'icon' => 'trending-up',
								],
							],
							'process' => [
								[
									'id' => 'ai-step-1',
									'title' => 'Préparation & Paramétrage',
									'description' => 'Préparation du projet et configuration des paramètres IA.',
									'icon' => 'circle',
									'details' => [
										'Collecte des images de référence et directives stylistiques',
										'Définition des paramètres de génération et contraintes',
										'Briefing créatif détaillé sur les objectifs',
									],
								],
								[
									'id' => 'ai-step-2',
									'title' => 'Génération Initiale',
									'description' => 'Génération des premières variantes par l\'IA.',
									'icon' => 'circle',
									'details' => [
										'Génération de multiples variantes de styles',
										'Exploration de différentes perspectives et configurations',
										'Création de variations de matériaux et environnement',
									],
								],
								[
									'id' => 'ai-step-3',
									'title' => 'Sélection & Affinement',
									'description' => 'Évaluation et sélection des meilleures générations.',
									'icon' => 'circle',
									'details' => [
										'Critique créative des générations',
										'Sélection des meilleures variantes',
										'Affinement des paramètres pour améliorer les résultats',
									],
								],
								[
									'id' => 'ai-step-4',
									'title' => 'Post-Production & Livraison',
									'description' => 'Retouches finales et préparation pour la présentation.',
									'icon' => 'circle',
									'details' => [
										'Post-production légère pour parfaire les images',
										'Ajustement couleur et composition finale',
										'Livraison en multiples formats et résolutions',
									],
								],
							],
							'relatedProjects' => [],
							'icon' => 'sparkles',
							'category' => 'Innovation',
							'ctaLabel' => 'Demander un devis',
							'ctaHref' => '/contact',
						],
						[
							'slug' => 'virtual-experiences',
							'title' => 'Expériences Virtuelles',
							'tagline' => 'Environnements immersifs interactifs et expériences VR',
							'description' => 'Créez des expériences virtuelles complètes et interactives pour vos projets. De l\'immobilier au design d\'intérieur, nos environnements virtuels permettent une exploration intuitive et immersive de vos créations architecturales.',
							'heroImage' => [
								'id' => 'service-hero-vr-experience',
								'src' => 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?auto=format&fit=crop&w=2070&q=80',
								'alt' => 'Expérience virtuelle immersive en réalité virtuelle',
							],
							'benefits' => [
								[
									'id' => 'benefit-vr-1',
									'title' => 'Interaction Complète',
									'description' => 'Exploration entièrement interactive permettant au visiteur de naviguer librement dans l\'espace.',
									'icon' => 'hand',
								],
								[
									'id' => 'benefit-vr-2',
									'title' => 'Simulation Réaliste',
									'description' => 'Physiques réalistes et interaction avec les objets pour une sensation d\'authenticité maximale.',
									'icon' => 'zap',
								],
								[
									'id' => 'benefit-vr-3',
									'title' => 'Multi-Plateforme',
									'description' => 'Déploiement sur desktop, mobile, tablette et casques VR pour une accessibilité maximale.',
									'icon' => 'monitor',
								],
								[
									'id' => 'benefit-vr-4',
									'title' => 'Engagement Élevé',
									'description' => 'Expériences mémorables créant un lien émotionnel fort avec votre projet.',
									'icon' => 'heart',
								],
							],
							'process' => [
								[
									'id' => 'vr-step-1',
									'title' => 'Design d\'Expérience',
									'description' => 'Conception de l\'expérience utilisateur et de la narration.',
									'icon' => 'circle',
									'details' => [
										'Définition des parcours de visite et interactions',
										'Conception de l\'interface utilisateur intuitive',
										'Planification des éléments interactifs et scénarios',
									],
								],
								[
									'id' => 'vr-step-2',
									'title' => 'Développement Technique',
									'description' => 'Développement de l\'environnement virtuel interactif.',
									'icon' => 'circle',
									'details' => [
										'Création du modèle 3D optimisé pour la performance',
										'Implémentation des interactions et mécaniques de jeu',
										'Intégration des systèmes de physique et collision',
									],
								],
								[
									'id' => 'vr-step-3',
									'title' => 'Intégration & Optimisation',
									'description' => 'Optimisation pour différentes plateformes.',
									'icon' => 'circle',
									'details' => [
										'Optimisation des performances pour mobile et VR',
										'Tests de compatibilité multi-plateforme',
										'Ajustement de la qualité graphique selon la plateforme',
									],
								],
								[
									'id' => 'vr-step-4',
									'title' => 'Déploiement & Support',
									'description' => 'Déploiement et support continu de l\'expérience.',
									'icon' => 'circle',
									'details' => [
										'Déploiement sur les plateformes ciblés',
										'Tests utilisateurs et retours',
										'Support technique et mises à jour futures',
									],
								],
							],
							'relatedProjects' => [],
							'icon' => 'globe',
							'category' => 'Expérience',
							'ctaLabel' => 'Demander un devis',
							'ctaHref' => '/contact',
						],
					],